name: Update README with Project Links

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script to update README
        run: python generate_readme.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Updated README with project links"

      - name: Push changes
        run: |
          git remote set-url origin https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
          git push origin main
